# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"

permissions: {}

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    permissions:
      contents: "write"

    steps:
      - name: "Determine tag"
        id: "determine-tag"
        run: "echo \"tag=${GITHUB_REF#refs/tags/}\" >> $GITHUB_OUTPUT"

      - name: "Create release"
        uses: "softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda" # v3.0.0
        with:
          draft: false
          name: "${{ steps.determine-tag.outputs.tag }}"
          prerelease: false
          tag_name: "${{ steps.determine-tag.outputs.tag }}"
          token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
